# Metrics computed during training, validation and testing.
- name: accuracy
  _target_: cryocast.metrics.IceNetAccuracyPerForecastDay
- name: centroid_error
  _target_: cryocast.metrics.CentroidErrorPerForecastDay
- name: diiee
  _target_: cryocast.metrics.DistanceAveragedIceEdgeErrorPerForecastDay
- name: fss_neighbourhood_size_1
  _target_: cryocast.metrics.FractionalSkillScorePerForecastDay
  neighbourhood_size: 1
- name: fss_neighbourhood_size_15
  _target_: cryocast.metrics.FractionalSkillScorePerForecastDay
  neighbourhood_size: 15
- name: fss_neighbourhood_size_5
  _target_: cryocast.metrics.FractionalSkillScorePerForecastDay
  neighbourhood_size: 5
- name: iiee
  _target_: cryocast.metrics.IntegratedIceEdgeErrorPerForecastDay
- name: mae
  _target_: cryocast.metrics.MAEPerForecastDay
- name: rmse
  _target_: cryocast.metrics.RMSEPerForecastDay
- name: sieerror
  _target_: cryocast.metrics.SeaIceExtentErrorPerForecastDay
- name: spatial_mean_ground_truth
  _target_: cryocast.metrics.SpatialMeanGroundTruthPerForecastDay
- name: spatial_mean_prediction
  _target_: cryocast.metrics.SpatialMeanPredictionPerForecastDay
- name: ssim
  _target_: cryocast.metrics.SSIMPerForecastDay
